### get usuarios
GET http://localhost:3000/api/usuario/ HTTP/1.1

### insertar usuario
POST http://localhost:3000/api/usuario/insert HTTP/1.1
Content-Type: application/json

{
	"correo": "em",
	"contrasena": "pa"
}

### register
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
	"user": "ema",
	"pass": "pass"
}

### login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json
Cookie: session=j%3A%7B%22id%22%3A%22827052d9-580c-4f61-91c9-fb2e78e658cd%22%2C%22user%22%3A%22emaile%22%7D

{
	"user": "ema",
	"pass": "pass"
}

### renew session with a cookie name session
POST  http://localhost:3000/api/auth/login/renew HTTP/1.1
Content-Type: application/json
Cookie: session=j%3A%7B%22id%22%3A%22dcb282b5-d35b-44f9-b04a-611e4da055fc%22%2C%22user%22%3A%22emaile%22%7D; Max-Age=604800; Path=/; Expires=Sat, 25 Nov 2023 23:09:47 GMT

### get the Programas
GET http://localhost:3000/api/programa/ HTTP/1.1

### get Prgoramas by slug
GET http://localhost:3000/api/programa/slug/ciencia-de-la-computacion HTTP/1.1

### get area by id programa
GET http://localhost:3000/api/programa/area/p/1 HTTP/1.1

### get user count
GET http://localhost:3000/api/usuario/count HTTP/1.1

### get Aspirante count 
GET http://localhost:3000/api/aspirante/count HTTP/1.1

### ge logged user
GET http://localhost:3000/api/usuario/user HTTP/1.1
Cookie: session=j%3A%7B%22id%22%3A%22dcb282b5-d35b-44f9-b04a-611e4da055fc%22%2C%22user%22%3A%22emaile%22%7D; Max-Age=604800; Path=/; Expires=Sat, 25 Nov 2023 23:09:47 GMT